### ISSUE TITLE
Dynamic page creation

### ISSUE THREAD

**Issue by ibarake** [ibarake/ashley-custom-app#4]
# create pages based on meta objects

#### reference this:
docs: https://shopify.dev/docs/api/admin-rest/2022-04/resources/page
theme code: https://github.com/ibarake/shopify-dawn-sections

#### templates:
macro: https://github.com/ibarake/shopify-dawn-sections/blob/main/templates/page.macro-category.json
sub: https://github.com/ibarake/shopify-dawn-sections/blob/main/templates/page.sub-category.json

# tasks
- [x] check out the documentation and come up with a solution
- [x] branch out
- [x] create request(s)
- [x] Make the page creation check for pages and do it only if it was not done before
- [x] create page using template
- [x] make it dynamic for each subcategory or macrocategory
- [x] test page creation on metaobject creation
- [x] test pages are created without opening the app

## above should define the functionality

- [x] do the same for the other metaobject

## is done! but...

- [ ] #5

**Comment by ibarake** [comment]
![image](https://user-images.githubusercontent.com/59149750/220204171-48df45f1-2b8e-4349-a5af-ee33a52fbcf9.png)
